# Generated by Django 4.2 on 2023-05-08 14:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TWP4', '0003_templateexercise_worktemplate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='templateExercise',
            new_name='Exercise',
        ),
        migrations.RenameModel(
            old_name='studentGroup',
            new_name='Group',
        ),
        migrations.RenameModel(
            old_name='workTemplate',
            new_name='Template',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
