# Generated by Django 4.2 on 2023-05-08 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TWP4', '0004_rename_templateexercise_exercise_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='templateExercises',
        ),
        migrations.AddField(
            model_name='template',
            name='exercises',
            field=models.ManyToManyField(blank=True, to='TWP4.exercise'),
        ),
    ]
