# Generated by Django 4.2 on 2023-05-10 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TWP4', '0005_remove_template_templateexercises_template_exercises'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('comment', models.TextField(blank=True)),
                ('startdate', models.DateTimeField(blank=True)),
                ('finishdate', models.DateTimeField(blank=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TWP4.group')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TWP4.template')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True)),
                ('ask', models.TextField()),
                ('solution', models.TextField(blank=True)),
                ('rightanswer', models.TextField()),
                ('answer', models.TextField(blank=True)),
                ('answerdate', models.DateTimeField(blank=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TWP4.work')),
            ],
        ),
    ]
